#!/usr/bin/env bash

## Update LIBEXEC inside the script (not the best way...)
sed -E -i '' 's/LIBEXEC="\.\.\/libexec"/LIBEXEC="src\/genpkg\/libexec"/g' src/genpkg/genpkg

./src/genpkg/genpkg "$@"

## Restore LIBEXEC inside the script (not the best way...)
sed -E -i '' 's/LIBEXEC="src\/genpkg\/libexec"/LIBEXEC="\.\.\/libexec"/g' src/genpkg/genpkg
